In [2]:
import pandas as pd
score = pd.Series([95,90,85,90,95])
score

0    95
1    90
2    85
3    90
4    95
dtype: int64

In [9]:

df = pd.DataFrame({'name':['장은실','오경선','양숙희'],'score':[90,88,85],'dept':['com','eng','math']})
df

  name  score  dept
0  장은실     90   com
1  오경선     88   eng
2  양숙희     85  math

In [14]:
df = pd.read_csv('angel.csv')
df

,name,Age,Overall rating,Potential,Team & Contract,ID,Height,Weight,foot,Best overall,...,GK Reflexes,Total stats,Base stats,International reputation,Pace / Diving,Shooting / Handling,Passing / Kicking,Dribbling / Reflexes,Defending / Pace,Unnamed: 64
0,A. Younes LM CAM,29.0,73,73,Al Ettifaq,205966.0,"170cm / 5'7""",71kg / 157lbs,Right,73.0,...,15,1842.0,387.0,1.0,71.0,67.0,70.0,79.0,38.0,NaN
1,NaN,NaN,NaN,NaN,2022 ~ 2024,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,R. Sessegnon LB LWB,23.0,75,80,Tottenham Hotspur,235883.0,"178cm / 5'10""",70kg / 154lbs,Left,77.0,...,7,1960.0,425.0,1.0,78.0,64.0,72.0,76.0,71.0,NaN
3,NaN,NaN,NaN,NaN,2019 ~ 2025,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mikel Merino CM CAM,27.0,84,85,Real Sociedad,225193.0,"189cm / 6'2""",83kg / 183lbs,Left,85.0,...,14,2282.0,480.0,2.0,72.0,79.0,82.0,82.0,83.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,NaN,NaN,NaN,NaN,2017 ~ 2026,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,S. Tonali CDM CM,23.0,86,89,Newcastle United,241096.0,"181cm / 5'11""",79kg / 174lbs,Right,87.0,...,7,2279.0,485.0,3.0,84.0,74.0,81.0,81.0,82.0,NaN
995,NaN,NaN,NaN,NaN,2023 ~ 2028,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,M. Taremi ST,30.0,81,81,Porto,241788.0,"185cm / 6'1""",83kg / 183lbs,Right,81.0,...,8,1985.0,426.0,2.0,78.0,81.0,75.0,81.0,38.0,NaN
997,NaN,NaN,NaN,NaN,2020 ~ 2024,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.sort_values(by='Age')

,name,Age,Overall rating,Potential,Team & Contract,ID,Height,Weight,foot,Best overall,...,GK Reflexes,Total stats,Base stats,International reputation,Pace / Diving,Shooting / Handling,Passing / Kicking,Dribbling / Reflexes,Defending / Pace,Unnamed: 64
176,Pau Cubarsí CB,16.0,66,85,FC Barcelona,278046.0,"182cm / 6'0""",75kg / 165lbs,Right,68.0,...,14,1459.0,322.0,1.0,67.0,23.0,46.0,56.0,67.0,NaN
958,L. Miller CM,16.0,64+1,84+1,Motherwell,275522.0,"182cm / 6'0""",72kg / 159lbs,Right,66.0,...,12,1723.0,370.0,1.0,72.0,57.0,63.0,65.0,50.0,NaN
716,L. Vušković CB,16.0,62,86,Radomiak Radom,275192.0,"193cm / 6'4""",86kg / 190lbs,Right,64.0,...,12,1634.0,362.0,1.0,61.0,61.0,50.0,57.0,58.0,NaN
598,L. Vušković CB,16.0,62,86,Radomiak Radom,275192.0,"193cm / 6'4""",86kg / 190lbs,Right,64.0,...,12,1634.0,362.0,1.0,61.0,61.0,50.0,57.0,58.0,NaN
44,J. Hato CB LB,17.0,73,88,Ajax,272978.0,"182cm / 6'0""",76kg / 168lbs,Left,75.0,...,9,1820.0,403.0,1.0,85.0,39.0,66.0,71.0,73.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,NaN,NaN,NaN,NaN,2019 ~ 2028,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
991,NaN,NaN,NaN,NaN,2017 ~ 2026,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
993,NaN,NaN,NaN,NaN,2017 ~ 2026,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,NaN,NaN,NaN,NaN,2023 ~ 2028,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN,2020 ~ 2024,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN